name: vps
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
uses: actions/checkout@v4
name: run vps
        sudo curl -sSf https://sshx.io/get | sudo sh -s run
